# Default still is generated into branding/wallpapers/default.png
# and installed to /usr/share/backgrounds/codalinux/default.png.

preload = /usr/share/backgrounds/codalinux/default.png
wallpaper = ,/usr/share/backgrounds/codalinux/default.png
splash = false
