# CodaLinux hyprlock stub.
# https://wiki.hypr.land/Hypr-Ecosystem/hyprlock/

general {
    hide_cursor = true
}

background {
    # TODO: branding/wallpapers/default.png
    color = rgba(18, 18, 20, 1.0)
}

input-field {
    monitor =
    size = 280, 48
    placeholder_text = <i>CodaLinux</i>
}
