#!/usr/bin/env bash
# Compose packages/*.txt into archiso and archinstall consumers.
# nvidia.txt, optional-cups.txt, and ags-build-deps.txt stay opt-in.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

emit() {
  local dest="$1"
  shift
  {
    echo "# Generated by scripts/compose-package-lists.sh — edit packages/*.txt, then re-run."
    echo "# Official Arch core/extra names only. Do not add a Coda repo or AUR packages."
    echo
    for list in "$@"; do
      echo "# --- packages/${list} ---"
      grep -vE '^\s*(#|$)' "${root}/packages/${list}" || true
      echo
    done
  } | awk 'seen[$0]++ && $0 !~ /^#/ && NF { next } { print }' > "${dest}"
}

emit "${root}/archiso/packages.x86_64" \
  base.txt hardware.txt network.txt desktop.txt apps.txt live.txt

emit "${root}/install/packages.txt" \
  base.txt hardware.txt network.txt desktop.txt apps.txt

python3 - "${root}/install/packages.txt" "${root}/install/user_configuration.json" <<'PY'
import json
import sys

list_path, json_path = sys.argv[1], sys.argv[2]
packages = []
with open(list_path, encoding="utf-8") as fh:
    for raw in fh:
        line = raw.split("#", 1)[0].strip()
        if line:
            packages.append(line)
with open(json_path, encoding="utf-8") as fh:
    cfg = json.load(fh)
cfg["packages"] = packages
with open(json_path, "w", encoding="utf-8") as fh:
    json.dump(cfg, fh, indent=2)
    fh.write("\n")
PY

echo "Wrote archiso/packages.x86_64, install/packages.txt, install/user_configuration.json"
